-- db/create.sql

-- =========================================================
--  EXTENSION
-- =========================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================
--  CORE: USERS (Hem Auth hem Profil)
-- =========================================================
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT,
    birth_year INT,                 -- AI yaş analizi için buraya taşıdık
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
--  CORE: DEVICE
-- =========================================================
CREATE TABLE device (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform TEXT,
    model TEXT,
    os_version TEXT,
    enrolled_at TIMESTAMPTZ DEFAULT NOW(),
    revoked_at TIMESTAMPTZ
);

-- =========================================================
--  CORE: APP CATEGORY
-- =========================================================
CREATE TABLE app_category (
    id SERIAL PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,       -- 'social', 'video', 'games'
    display_name TEXT NOT NULL
);

-- =========================================================
--  CORE: APP CATALOG
-- =========================================================
CREATE TABLE app_catalog (
    package_name TEXT PRIMARY KEY,
    app_name TEXT NOT NULL,
    category_id INT,
    CONSTRAINT fk_app_catalog_category
        FOREIGN KEY (category_id) REFERENCES app_category(id)
);

-- =========================================================
--  CORE: USER SETTINGS (Eski child_settings)
-- =========================================================
CREATE TABLE user_settings (
    user_id UUID PRIMARY KEY,
    timezone VARCHAR,               
    nightly_start TIME,             
    nightly_end TIME,               
    min_night_minutes INT,
    weekend_relax_pct INT,
    min_session_seconds INT,
    session_app_seconds INT,
    daily_limit_minutes INT DEFAULT 120,
    CONSTRAINT fk_user_settings_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =========================================================
--  CORE: APP SESSION
-- =========================================================
CREATE TABLE app_session (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL,
    device_id UUID NOT NULL,
    package_name TEXT NOT NULL,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    source VARCHAR,
    payload JSONB,
    occurred_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_app_session_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_session_device
        FOREIGN KEY (device_id) REFERENCES device(id) ON DELETE CASCADE,
    CONSTRAINT unique_session_entry UNIQUE (user_id, device_id, package_name, started_at)
);
-- =========================================================
--  CORE: DAILY USAGE LOG
-- =========================================================

CREATE TABLE daily_usage_log (
    user_id UUID NOT NULL,
    device_id UUID NOT NULL,
    usage_date DATE NOT NULL,
    package_name TEXT NOT NULL,
    app_name TEXT,
    total_seconds INT DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT pk_daily_usage PRIMARY KEY (user_id, device_id, usage_date, package_name),
    
    CONSTRAINT fk_daily_usage_user 
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_daily_usage_device
        FOREIGN KEY (device_id) REFERENCES device(id) ON DELETE CASCADE
);

-- =========================================================
--  ANALYTICS: DAILY FEATURES (AI Girdisi)
-- =========================================================
CREATE TABLE feature_daily (
    user_id UUID NOT NULL,          -- Refactor: child_id -> user_id
    date DATE NOT NULL,
    total_minutes INT NOT NULL,
    night_minutes INT,
    gaming_ratio DECIMAL(4,2),
    social_ratio DECIMAL(4,2),
    session_count INT,
    weekday SMALLINT,
    weekend BOOLEAN,

    PRIMARY KEY (user_id, date),
    CONSTRAINT fk_feature_daily_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =========================================================
--  AI META: RISK DIMENSION & LEVEL
-- =========================================================
CREATE TABLE risk_dimension (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR NOT NULL UNIQUE,    -- 'sleep', 'gaming', 'social'
    display_name VARCHAR
);

CREATE TABLE risk_level (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR NOT NULL UNIQUE,    -- 'low', 'medium', 'high'
    rank SMALLINT NOT NULL
);

-- =========================================================
--  AI: RISK ASSESSMENT (Risk Değerlendirmesi)
-- =========================================================
CREATE TABLE risk_assessment (
    user_id UUID NOT NULL,          -- Refactor: child_id -> user_id
    as_of_date DATE NOT NULL,
    dimension_id SMALLINT NOT NULL,
    level_id SMALLINT NOT NULL,
    prob DECIMAL(4,3),              -- Modelin risk olasılığı
    model_key VARCHAR,              -- 'v1_sleep_rf' vb.
    features JSONB,                 -- O anki snapshot

    PRIMARY KEY (user_id, as_of_date, dimension_id),

    CONSTRAINT fk_risk_assessment_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_risk_assessment_dim
        FOREIGN KEY (dimension_id) REFERENCES risk_dimension(id),
    CONSTRAINT fk_risk_assessment_level
        FOREIGN KEY (level_id) REFERENCES risk_level(id)
);

-- =========================================================
--  AI: WEEKLY FORECAST (Kullanım Tahmini)
-- =========================================================
CREATE TABLE weekly_forecast (
    user_id UUID NOT NULL,          -- Refactor: child_id -> user_id
    as_of_date DATE NOT NULL,
    horizon_week SMALLINT NOT NULL,
    scenario VARCHAR NOT NULL,      -- 'baseline', 'reduced'
    target VARCHAR,                 -- 'total_minutes'
    yhat_lo INT,
    yhat_hi INT,
    model_key VARCHAR,

    PRIMARY KEY (user_id, as_of_date, horizon_week, scenario),

    CONSTRAINT fk_weekly_forecast_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =========================================================
--  POLICY: RULE (Kurallar)
-- =========================================================
CREATE TABLE policy_rule (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL,          -- Refactor: child_id -> user_id
    source VARCHAR,                 -- 'ai', 'parent_manual'
    target_category_id INT,
    target_package TEXT,
    action VARCHAR,                 -- 'limit', 'block', 'warn'
    param_int INT,
    allow_mask INT,
    local_start TIME,
    local_end TIME,
    active BOOLEAN DEFAULT TRUE,
    effective_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,

    CONSTRAINT fk_policy_rule_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_policy_rule_category
        FOREIGN KEY (target_category_id) REFERENCES app_category(id)
);

-- =========================================================
--  POLICY: EFFECT (Etki Analizi)
-- =========================================================
CREATE TABLE policy_effect (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL,          -- Refactor: child_id -> user_id
    policy_rule_id BIGINT NOT NULL,
    metric VARCHAR,
    window_pre INT,
    window_post INT,
    effect DECIMAL(6,3),
    ci_low DECIMAL(6,3),
    ci_high DECIMAL(6,3),
    p_value DECIMAL(6,3),
    as_of_date DATE,
    model_key VARCHAR,

    CONSTRAINT fk_policy_effect_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_policy_effect_rule
        FOREIGN KEY (policy_rule_id) REFERENCES policy_rule(id)
);

-- =========================================================
--  AUDIT: ENFORCEMENT LOG
-- =========================================================
CREATE TABLE enforcement_log (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL,          -- Refactor: child_id -> user_id
    package_name TEXT,
    action VARCHAR,
    action_at TIMESTAMPTZ DEFAULT NOW(),
    meta JSONB,

    CONSTRAINT fk_enforcement_log_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);