-- =========================================================
--  EXTENSION
-- =========================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================
--  CORE: USERS
-- =========================================================
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
--  CORE: CHILD
-- =========================================================
CREATE TABLE IF NOT EXISTS child (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    parent_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    full_name TEXT,
    birth_year INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =========================================================
--  CORE: DEVICE
-- =========================================================
CREATE TABLE device (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform TEXT,
    model TEXT,
    os_version TEXT,
    enrolled_at TIMESTAMPTZ DEFAULT NOW(),
    revoked_at TIMESTAMPTZ
);

-- =========================================================
--  CORE: APP CATEGORY
-- =========================================================
CREATE TABLE app_category (
    id SERIAL PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,       -- 'social', 'video', 'games' ...
    display_name TEXT NOT NULL
);

-- =========================================================
--  CORE: APP CATALOG
-- =========================================================
CREATE TABLE app_catalog (
    package_name TEXT PRIMARY KEY,  -- Android packageName
    app_name TEXT NOT NULL,
    category_id INT,
    CONSTRAINT fk_app_catalog_category
        FOREIGN KEY (category_id) REFERENCES app_category(id)
);

-- =========================================================
--  CORE: CHILD SETTINGS
-- =========================================================
CREATE TABLE child_settings (
    child_id UUID PRIMARY KEY,
    timezone VARCHAR,               -- 'Europe/Istanbul'
    nightly_start TIME,             -- ör: 21:30
    nightly_end TIME,               -- ör: 07:00
    min_night_minutes INT,
    weekend_relax_pct INT,          -- %20 esneklik gibi
    min_session_seconds INT,
    session_app_seconds INT,
    CONSTRAINT fk_child_settings_child
        FOREIGN KEY (child_id) REFERENCES users(id)
);

-- =========================================================
--  CORE: APP SESSION (usage oturumları)
-- =========================================================
CREATE TABLE app_session (
    id BIGSERIAL PRIMARY KEY,
    child_id UUID NOT NULL,
    device_id UUID NOT NULL,
    package_name TEXT NOT NULL,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    source VARCHAR,
    payload JSONB,
    occurred_at TIMESTAMPTZ DEFAULT NOW(),

    -- Sadece users ve device tablolarına bağladık, catalog şartını kaldırdık.
    CONSTRAINT fk_app_session_child
        FOREIGN KEY (child_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_session_device
        FOREIGN KEY (device_id) REFERENCES device(id) ON DELETE CASCADE
    CONSTRAINT unique_session_entry UNIQUE (child_id, device_id, package_name, started_at)
    
);

-- =========================================================
--  CORE: FEATURE_DAILY (günlük özet feature'lar)
-- =========================================================
CREATE TABLE feature_daily (
    child_id UUID NOT NULL,
    date DATE NOT NULL,
    total_minutes INT NOT NULL,
    night_minutes INT,
    gaming_ratio DECIMAL(4,2),
    social_ratio DECIMAL(4,2),
    session_count INT,
    weekday SMALLINT,               -- 1=pzt ... 7=paz
    weekend BOOLEAN,

    PRIMARY KEY (child_id, date),
    CONSTRAINT fk_feature_daily_child
        FOREIGN KEY (child_id) REFERENCES users(id)
);

-- =========================================================
--  AI META: RISK_DIMENSION
-- =========================================================
CREATE TABLE risk_dimension (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR NOT NULL UNIQUE,    -- 'sleep', 'gaming', 'social', ...
    display_name VARCHAR
);

-- =========================================================
--  AI META: RISK_LEVEL
-- =========================================================
CREATE TABLE risk_level (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR NOT NULL UNIQUE,    -- 'low', 'medium', 'high'
    rank SMALLINT NOT NULL          -- 1 < 2 < 3
);

-- =========================================================
--  AI: RISK_ASSESSMENT (çocuk x gün, boyut bazlı risk)
-- =========================================================
CREATE TABLE risk_assessment (
    child_id UUID NOT NULL,
    as_of_date DATE NOT NULL,
    dimension_id SMALLINT NOT NULL,
    level_id SMALLINT NOT NULL,
    prob DECIMAL(4,3),              -- modelin risk olasılığı
    model_key VARCHAR,              -- 'v1_sleep_rf', 'v1_gaming_rf' ...
    features JSONB,                 -- o güne dair feature snapshot

    PRIMARY KEY (child_id, as_of_date, dimension_id),

    CONSTRAINT fk_risk_assessment_child
        FOREIGN KEY (child_id) REFERENCES users(id),
    CONSTRAINT fk_risk_assessment_dim
        FOREIGN KEY (dimension_id) REFERENCES risk_dimension(id),
    CONSTRAINT fk_risk_assessment_level
        FOREIGN KEY (level_id) REFERENCES risk_level(id)
);

-- =========================================================
--  AI: WEEKLY_FORECAST (kullanım tahmini)
-- =========================================================
CREATE TABLE weekly_forecast (
    child_id UUID NOT NULL,
    as_of_date DATE NOT NULL,
    horizon_week SMALLINT NOT NULL, -- 1,2,3 ... n hafta sonrası
    scenario VARCHAR NOT NULL,      -- 'baseline', 'reduced', ...
    target VARCHAR,                 -- 'total_minutes', 'night_minutes', ...
    yhat_lo INT,
    yhat_hi INT,
    model_key VARCHAR,              -- forecast modeli adı

    PRIMARY KEY (child_id, as_of_date, horizon_week, scenario),

    CONSTRAINT fk_weekly_forecast_child
        FOREIGN KEY (child_id) REFERENCES users(id)
);

-- =========================================================
--  POLICY: RULE (uygulanacak kural)
-- =========================================================
CREATE TABLE policy_rule (
    id BIGSERIAL PRIMARY KEY,
    child_id UUID NOT NULL,
    source VARCHAR,                 -- 'ai', 'parent_manual', ...
    target_category_id INT,         -- app_category.id
    target_package TEXT,            -- spesifik app
    action VARCHAR,                 -- 'limit', 'block', 'allow', 'warn'
    param_int INT,                  -- ör: max minutes
    allow_mask INT,                 -- binary flags vs. istersen
    local_start TIME,
    local_end TIME,
    active BOOLEAN,
    effective_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,

    CONSTRAINT fk_policy_rule_child
        FOREIGN KEY (child_id) REFERENCES users(id),
    CONSTRAINT fk_policy_rule_category
        FOREIGN KEY (target_category_id) REFERENCES app_category(id)
);

-- =========================================================
--  POLICY: EFFECT (kuralın etkisini ölçen log)
-- =========================================================
CREATE TABLE policy_effect (
    id BIGSERIAL PRIMARY KEY,
    child_id UUID NOT NULL,
    policy_rule_id BIGINT NOT NULL,
    metric VARCHAR,                 -- 'total_minutes', 'night_minutes', ...
    window_pre INT,                 -- kural öncesi gün sayısı
    window_post INT,                -- kural sonrası gün sayısı
    effect DECIMAL(6,3),
    ci_low DECIMAL(6,3),
    ci_high DECIMAL(6,3),
    p_value DECIMAL(6,3),
    as_of_date DATE,
    model_key VARCHAR,              -- etki tahmin modeli

    CONSTRAINT fk_policy_effect_child
        FOREIGN KEY (child_id) REFERENCES users(id),
    CONSTRAINT fk_policy_effect_rule
        FOREIGN KEY (policy_rule_id) REFERENCES policy_rule(id)
);

-- =========================================================
--  AUDIT: ENFORCEMENT_LOG (politika uygulama logu)
-- =========================================================
CREATE TABLE enforcement_log (
    id BIGSERIAL PRIMARY KEY,
    child_id UUID NOT NULL,
    package_name TEXT,
    action VARCHAR,                 -- 'blocked', 'limited', 'notified', ...
    action_at TIMESTAMPTZ DEFAULT NOW(),
    meta JSONB,

    CONSTRAINT fk_enforcement_log_child
        FOREIGN KEY (child_id) REFERENCES users(id),
    CONSTRAINT fk_enforcement_log_package
        FOREIGN KEY (package_name) REFERENCES app_catalog(package_name)
);
